# Generated by Django 3.2 on 2021-08-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=None, help_text='Name of the Profile.', max_length=128),
        ),
    ]
