# Generated by Django 3.2 on 2021-08-01 19:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profile_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'profile_type', 'name')},
        ),
    ]
