# Generated by Django 3.2 on 2021-08-08 14:58

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0003_auto_20210804_1959'),
        ('sellers', '0003_auto_20210804_1959'),
        ('users', '0004_auto_20210804_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the invoice. Only for user's reference.", max_length=128, verbose_name='name')),
                ('number_of_units', models.IntegerField(help_text='Number of units sold/transferred for this invoice.')),
                ('quantity_per_unit', models.IntegerField(help_text='Number of kgs sold/transferred for this invoice.')),
                ('quantity_measurement_unit', models.IntegerField(choices=[(1, 'Quintal'), (2, 'Kilogram'), (3, 'Pound'), (4, 'Lbs'), (5, 'Stone'), (6, 'Gallon'), (7, 'Litre')], default=1, max_length=2)),
                ('price_applied_to', models.IntegerField(choices=[(1, 'Quintal'), (2, 'Kilogram'), (3, 'Pound'), (4, 'Lbs'), (5, 'Stone'), (6, 'Gallon'), (7, 'Litre')], default=1, max_length=2)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Price as per price_applied_to.', max_digits=55)),
                ('commission_type', models.IntegerField(choices=[(1, 'Fixed'), (2, 'Percent')], default=1, max_length=2)),
                ('commission_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Value to be used for commission, It can be any of the type based on commission type.', max_digits=55)),
                ('commission_applied_to', models.IntegerField(choices=[(1, 'Per Quintal'), (2, 'Per Kilogram'), (3, 'Per Pound'), (4, 'Per Lbs'), (5, 'Per Stone'), (6, 'Per Gallon'), (7, 'Per Litre')], default=1, help_text='Commission applied to.', max_length=2)),
                ('include_price_in_calculations', models.BooleanField(default=False, help_text='whether to include price in commission calculation or not?')),
                ('calculated_commission', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Calculated commission value.', max_digits=55)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('buyer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buyers.buyer')),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('seller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
