# Generated by Django 3.2 on 2021-08-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='commission_applied_to',
            field=models.IntegerField(choices=[(1, 'Per Quintal'), (2, 'Per Kilogram'), (3, 'Per Pound'), (4, 'Per Lbs'), (5, 'Per Stone'), (6, 'Per Gallon'), (7, 'Per Litre')], default=1, help_text='Commission applied to.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='commission_type',
            field=models.IntegerField(choices=[(1, 'Fixed'), (2, 'Percent')], default=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_applied_to',
            field=models.IntegerField(choices=[(1, 'Quintal'), (2, 'Kilogram'), (3, 'Pound'), (4, 'Lbs'), (5, 'Stone'), (6, 'Gallon'), (7, 'Litre')], default=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity_measurement_unit',
            field=models.IntegerField(choices=[(1, 'Quintal'), (2, 'Kilogram'), (3, 'Pound'), (4, 'Lbs'), (5, 'Stone'), (6, 'Gallon'), (7, 'Litre')], default=1),
        ),
    ]
