# Generated by Django 3.2 on 2021-08-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20210808_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='price_applied_to',
            field=models.IntegerField(choices=[(1, 'Per Quintal'), (2, 'Per Kilogram'), (3, 'Per Pound'), (4, 'Per Lbs'), (5, 'Per Stone'), (6, 'Per Gallon'), (7, 'Per Litre'), (8, 'Per Unit')], default=8),
        ),
    ]
