# Generated by Django 3.2 on 2021-08-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_price_applied_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='commission_applied_to',
            field=models.IntegerField(choices=[(1, 'Per Quintal'), (2, 'Per Kilogram'), (3, 'Per Pound'), (4, 'Per Lbs'), (5, 'Per Stone'), (6, 'Per Gallon'), (7, 'Per Litre'), (8, 'Per Unit')], default=1, help_text='Price applied to what type of unit (Per Quintal/Per Kg/Whole Unit).'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='commission_type',
            field=models.IntegerField(choices=[(1, 'Fixed'), (2, 'Percent')], default=1, help_text='Is commission fixed or in per cent.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_applied_to',
            field=models.IntegerField(choices=[(1, 'Per Quintal'), (2, 'Per Kilogram'), (3, 'Per Pound'), (4, 'Per Lbs'), (5, 'Per Stone'), (6, 'Per Gallon'), (7, 'Per Litre'), (8, 'Per Unit')], default=8, help_text='Price applied to what type of unit (Per Quintal/Per Kg/Whole Unit).'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity_measurement_unit',
            field=models.IntegerField(choices=[(1, 'Quintal'), (2, 'Kilogram'), (3, 'Pound'), (4, 'Lbs'), (5, 'Stone'), (6, 'Gallon'), (7, 'Litre')], default=1, help_text='Measure unit of a unit like Quintal/Kgs.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity_per_unit',
            field=models.IntegerField(help_text='Number of Quintal/KGs per unit.'),
        ),
    ]
