# Generated by Django 3.2 on 2021-08-14 08:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20210814_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='price_applied_to',
            new_name='price_for_commission_applied_to',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_applied_to',
            field=models.IntegerField(choices=[(1, 'Per Quintal'), (2, 'Per Kilogram'), (3, 'Per Pound'), (4, 'Per Lbs'), (5, 'Per Stone'), (6, 'Per Gallon'), (7, 'Per Litre'), (8, 'Per Unit')], default=1, help_text='Discount applied to what type of unit (Per Quintal/Per Kg/Whole Unit).'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.IntegerField(choices=[(1, 'Fixed'), (2, 'Percent')], default=1, help_text='Is discount fixed or in per cent.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Value to be used for discount, It can be of any type based on discount type.', max_digits=55),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price_for_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Price for commission as per price_for_commission_applied_to.', max_digits=55),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total price for this invoice.', max_digits=55),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='commission_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Value to be used for commission, It can be of any type based on commission type.', max_digits=55),
        ),
    ]
