# Generated by Django 3.2 on 2021-08-14 15:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20210814_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount_applied_to',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='include_price_in_calculations',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Value to be used for discount, It can be of any type based on discount type.', max_digits=55, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(blank=True, default=None, help_text="Name of the invoice. Only for user's reference.", max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_for_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Price for commission as per price_for_commission_applied_to.', max_digits=55, null=True),
        ),
    ]
