# Generated by Django 3.2 on 2021-08-15 03:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20210814_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='calculated_commission',
            new_name='calculated_buyer_commission',
        ),
        migrations.AddField(
            model_name='invoice',
            name='calculated_seller_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Calculated commission value.', max_digits=55),
        ),
    ]
