# Generated by Django 3.2 on 2021-08-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_auto_20210820_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, help_text='If the Invoice is paid.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='partial_paid',
            field=models.BooleanField(default=False, help_text='If the Invoice is partially paid.'),
        ),
    ]
