# Generated by Django 3.2 on 2021-09-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_minimum_quantity'),
        ('invoices', '0017_auto_20210904_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
