# Generated by Django 3.1.3 on 2021-09-12 15:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_invoice_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer_commission_paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total Buyer commission paid for this invoice.', max_digits=55, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_commission_paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total Seller commission paid for this invoice.', max_digits=55, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
