# Generated by Django 3.1.3 on 2021-09-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_alter_seller_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
