# Generated by Django 3.2 on 2021-08-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('buyers', '0003_auto_20210804_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
