# Generated by Django 3.2 on 2021-09-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210804_1959'),
        ('buyers', '0004_buyer_products'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buyer',
            unique_together={('name', 'contact_phone_number', 'profile')},
        ),
    ]
