# Generated by Django 3.1.3 on 2021-09-21 21:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20210912_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_commission_type', models.IntegerField(choices=[(1, 'Fixed'), (2, 'Percent')], default=1, help_text='Is seller commission fixed or in per cent.')),
                ('seller_commission_value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Value to be used for seller commission, It can be of any type based on commission type.', max_digits=55, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('seller_commission_applied_to', models.IntegerField(blank=True, choices=[(1, 'Per Quintal'), (2, 'Per Kilogram'), (3, 'Per Pound'), (4, 'Per Ounce'), (5, 'Per Stone'), (6, 'Per Gallon'), (7, 'Per Litre'), (8, 'Per Unit')], default=1, help_text='Seller commission applied to what type of unit (Per Quintal/Per Kg/Whole Unit).', null=True)),
                ('buyer_commission_type', models.IntegerField(choices=[(1, 'Fixed'), (2, 'Percent')], default=1, help_text='Is buyer commission fixed or in per cent.')),
                ('buyer_commission_value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Value to be used for buyer commission, It can be of any type based on commission type.', max_digits=55, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('buyer_commission_applied_to', models.IntegerField(blank=True, choices=[(1, 'Per Quintal'), (2, 'Per Kilogram'), (3, 'Per Pound'), (4, 'Per Ounce'), (5, 'Per Stone'), (6, 'Per Gallon'), (7, 'Per Litre'), (8, 'Per Unit')], default=1, help_text='Buyer commission applied to what type of unit (Per Quintal/Per Kg/Whole Unit).', null=True)),
                ('seller_price_for_commission', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Seller price for commission as per price_for_commission_applied_to.', max_digits=55, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('seller_price_for_commission_applied_to', models.IntegerField(blank=True, choices=[(1, 'Per Quintal'), (2, 'Per Kilogram'), (3, 'Per Pound'), (4, 'Per Ounce'), (5, 'Per Stone'), (6, 'Per Gallon'), (7, 'Per Litre'), (8, 'Per Unit')], default=8, help_text='Seller price used for commission calculations, applied to what type of unit (Per Quintal/Per Kg/Whole Unit).', null=True)),
                ('buyer_price_for_commission', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Buyer price for commission as per price_for_commission_applied_to.', max_digits=55, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('buyer_price_for_commission_applied_to', models.IntegerField(blank=True, choices=[(1, 'Per Quintal'), (2, 'Per Kilogram'), (3, 'Per Pound'), (4, 'Per Ounce'), (5, 'Per Stone'), (6, 'Per Gallon'), (7, 'Per Litre'), (8, 'Per Unit')], default=8, help_text='Buyer price used for commission calculations, applied to what type of unit (Per Quintal/Per Kg/Whole Unit).', null=True)),
                ('profile', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
