# Generated by Django 3.1.3 on 2021-09-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210912_1502'),
        ('profilesettings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='ProfileSettings',
        ),
    ]
