# Generated by Django 3.1.3 on 2021-09-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesettings', '0002_auto_20210925_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilesettings',
            options={'verbose_name': 'ProfileSetting', 'verbose_name_plural': 'ProfileSettings'},
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='only_buyer_commission',
            field=models.BooleanField(default=False, help_text='Deduct commission only from buyer.'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='only_seller_commission',
            field=models.BooleanField(default=False, help_text='Deduct commission only from seller.'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='separate_commission_for_seller_and_buyer',
            field=models.BooleanField(default=False, help_text='Deduct diffrent commissions from seller and buyer.'),
        ),
    ]
