# Generated by Django 3.1.3 on 2021-09-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesettings', '0003_auto_20210925_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='set_commission_per_invoice',
            field=models.BooleanField(default=True, help_text='Set commission for each invoice.'),
        ),
    ]
