# Generated by Django 3.2 on 2021-07-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, default='', help_text='Address line 1.', max_length=128, null=True, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, default='', help_text='Address line 2.', max_length=128, null=True, verbose_name='address line 2')),
                ('city', models.CharField(blank=True, default='', help_text='City name.', max_length=128, null=True, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, default=None, help_text='Postal code.', max_length=10, null=True, verbose_name='postal code')),
                ('verified', models.BooleanField(default=False, help_text='Is the address verified?', verbose_name='verified')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
