# Generated by Django 3.2 on 2021-08-28 06:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Minimum quantity of the product that must be ordered or bought.', max_digits=55, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
